<?php
namespace GPM\Model;

use xPDO\xPDO;

/**
 * Class APIKey
 *
 * @property integer $package
 * @property string $key
 * @property array $permissions
 * @property string $createdon
 *
 * @property GitPackage $Package
 *
 * @package GPM\Model
 */
class APIKey extends \xPDO\Om\xPDOSimpleObject
{
    public function set($k, $v = null, $vType = '')
    {
        if ($k === 'key') return false;
        if ($k === 'createdon') return false;

        return parent::set($k, $v, $vType); // TODO: Change the autogenerated stub
    }

    public function save($cacheFlag = null)
    {
        if (empty($this->key)) {
            $key = bin2hex(random_bytes(32));
            while($this->xpdo->getCount(self::class, ['key' => $key]) > 0) {
                $key = bin2hex(random_bytes(32));
            }

            $this->_fields['key'] = $key;
            $this->setDirty('key');
        }

        if ($this->isNew()) {
            $this->_fields['createdon'] = date('Y-m-d H:i:s');
            $this->setDirty('createdon');
        }

        return parent::save($cacheFlag);
    }


}
