<?php
/**
 * @var \MODX\Revolution\modX $modx
 * @var array $namespace
 */

// Include autoloader generated by your composer
require_once $namespace['path'] . 'vendor/autoload.php';

if (!$modx->services->has('{{$lowCaseName}}')) {
    // Register base class in the service container
    $modx->services->add('{{$lowCaseName}}', function($c) use ($modx) {
        return new \{{$namespace}}\{{$name}}($modx);
    });

    // Load packages model, uncomment if you have DB tables
    //$modx->addPackage('{{$namespace}}\Model', $namespace['path'] . 'src/', null, '{{$namespace}}\\');
}

// More about this file: https://docs.modx.com/3.x/en/extending-modx/namespaces#bootstrapping-services
